### ISSUE TITLE
The PHP SOAP extension (php-soap) is not installed/enabled

### ISSUE THREAD

**Issue by tomaszszkudlarek** [Icinga/icingaweb2-module-vsphere#24]
vSphere Module version 1.1.0
Director Version - latest
CentOS 7, 
php 5.4.16,
Soap Module installed (visible in all info commands, and tested via simple script which executes exactly the same condition - if class_exists ('SoapClient') - which is returning true)
No errors in httpd log.
Error comes when i try to add new import source.
Honestly i have no idea how to investigate this further.

**Comment by tomaszszkudlarek** [comment]
httpd as well as the whole server was restarted just to be sure

**Comment by SjamonDaal** [comment]
I've got the same issue over here.

**Comment by SjamonDaal** [comment]
Fixed it!
System was installing SOAP by default for PHP 5.4 but icingaweb2 is running on rh-php71 (Check in /etc/opt/rh what version you have installed)

`
[root@SDH-DRO-MON01 ~]# ls /etc/opt/rh
> rh-php71
`

For rh-php71: https://centos.pkgs.org/7/centos-sclo-rh/rh-php71-php-soap-7.1.8-1.el7.x86_64.rpm.html

Command:
`yum install rh-php71-php-soap`

**Comment by tomaszszkudlarek** [comment]
It's in fact 7.1, however i didn't solve the problem by installing it (and restarting httpd). But maybe in my case i require some additional configuration steps. I'll check it later. Thanks for a tip.

**Comment by SjamonDaal** [comment]
After just restarting the service it didn't work on my system. I've restarted the machine.

**Comment by sonicos** [comment]
For those of you having this issue after installing the aforementioned package and restarting apache, you're probably configured to use php-fpm. You'll need to run the following command:
`systemctl restart rh-php71-php-fpm.service`

**Comment by pdroz** [comment]
Confirmed on Centos 7.x the following works:
yum install rh-php71-php-soap
systemctl restart rh-php71-php-fpm.service

**Comment by pcasis** [comment]
Thx @sonicos 👍 
It works :)

**Comment by m4k5ym** [comment]
Small tip at the end:
If you are using PHP-FPM under CentOS and install some new extention you always have to restart the PHP-FPM daemon because it is taking care about PHP under CentOS.
